# Generated by Django 3.2 on 2023-07-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='freebies',
            field=models.CharField(max_length=200),
        ),
    ]
