# Generated by Django 3.2 on 2023-07-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_hotel_freebies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='freebies',
            field=models.JSONField(),
        ),
    ]
