# Generated by Django 3.2 on 2023-07-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='iframe',
            field=models.URLField(max_length=400),
        ),
    ]
