# Generated by Django 3.2 on 2023-07-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_hotel_iframe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
