# Generated by Django 3.2 on 2023-08-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='reviewQuality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='roomsGuests',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='airline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='arrivalTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='departTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='durationstring',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='fromTo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='froms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='passengerClass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(),
        ),
    ]
