# Generated by Django 3.2 on 2023-08-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
