# Generated by Django 3.2 on 2023-08-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
