# Generated by Django 3.2 on 2023-08-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20230819_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
