# Generated by Django 3.2 on 2023-08-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20230820_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
