# Generated by Django 3.2 on 2023-08-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
