# Generated by Django 3.2 on 2023-08-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
