# Generated by Django 3.2 on 2023-08-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
