# Generated by Django 3.2 on 2023-08-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_blog_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='paragraph',
            field=models.TextField(),
        ),
    ]
