# Generated by Django 3.2 on 2023-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_alter_blog_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='paragraph',
            new_name='paragraf',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
