# Generated by Django 3.2 on 2023-08-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
